### ISSUE TITLE
Missing "Location" data item in OA/OP

### ISSUE THREAD

**Issue by 15E601** [RDFBones/Phaleron-Pathologies#3]
It is not possible to enter locations for the OA/OP sections in the app. The spreadsheet however does ask for this item.
The Phaleron Scoring Key also states on the location data item: "This location scoring key will be used for all pathology sections except for “Bone Loss”, which has a separate location scoring key".

**Comment by cuboideum** [comment]
Fixed with commit https://github.com/RDFBones/Phaleron-Pathologies/commit/2a9af46fe425a67dd54d5f5e4da473fee09074e3.

**Comment by 15E601** [comment]
This fixes the issue in the ontology, but it is still not possible to enter these values. A change in the App interface is also necessary, is it not?

**Comment by zarquon42b** [comment]
It is not merged yet. You opened the issue in the ontology repo and here the problem is solved. 
There is a corresponding issue in the App and a PR has been issued: https://github.com/AnthroGraph/PBP-App/pull/29
So this issue here remains closed.
